name: id_class_source_ban
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  solid_lints:
    path: ../../../
