name: solid_lints_example
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.7.1
  solid_lints:
    path: ../
  test: ^1.25.14
