name: solid_lints
description:
  Lints for Dart and Flutter based on software industry standards and best
  practices.
version: 0.0.15
homepage: https://github.com/solid-software/solid_lints/

environment:
  sdk: '>=2.4.14 <4.0.0'

dependencies:
  dart_code_metrics: ^4.16.0
