name: solid_lints
description:
  Lints for Dart and Flutter based on software industry standards and best
  practices.
version: 0.3.3
homepage: https://github.com/solid-software/solid_lints/
documentation: https://solid-software.github.io/solid_lints/docs/intro
topics: [lints, linter, lint, analysis, analyzer]

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  analyzer: ^8.4.0
  collection: ^1.19.0
  custom_lint_builder: ^0.8.1
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3
  # These packages are required for pana analysis to run correctly
  flutter:
    sdk: flutter
  test: ^1.25.14

dev_dependencies:
  args: ^2.6.0
