name: solid_lints
description:
  Lints for Dart and Flutter based on software industry standards and best
  practices.
version: 0.1.0
homepage: https://github.com/solid-software/solid_lints/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^5.12.0
  collection: ^1.17.2
  custom_lint_builder: ^0.5.3
  path: ^1.8.3

dev_dependencies:
  # These packages are mandatory for some of tests
  flutter:
    sdk: flutter
  test: ^1.24.6

